Repository Igire-Rwanda/Saving-backend, pull requests merged in 2023-06, with the labels that each got.

#17 changes in controller side
  controllers/userRegisterController.js
Labels: ready to merge

#18 fixing deployment problems
  Routes/userRegisterRoutes.js
  controllers/userRegisterController.js
Labels: help wanted

#19 fix deployment
  Routes/expenseRoute.js
  index.js
Labels: help wanted

#21 changes after fixing hosting problems
  Routes/userRegisterRoutes.js
  controllers/userRegisterController.js
  index.js
Labels: ready to merge

#22 Getting only bankRoute
  controllers/userRegisterController.js
  index.js
  routes/bankroute.js
Labels: ready to merge

#20 Add expenses
  Models/bankModel.js
  Models/savingModel.js
  Routes/expenseRoute.js
  controllers/ExpenseController.js
  controllers/transferController.js
  controllers/userRegisterController.js
  index.js
  package-lock.json
  package.json
Labels: ready to merge

#29 V2 develop
  Models/savingModel.js
  Routes/expenseRoute.js
  Routes/homeRoute.js
  controllers/transferController.js
  controllers/userRegisterController.js
  index.js
  package.json
Labels: ready to merge

#30 V2 develop
  .env
  .gitignore
  Models/ExpenseModel.js
  Models/bankModel.js
  Models/goalModel.js
  Models/incomeModel.js
  Models/savingModel.js
  Models/signUpModel.js
  Models/teamsModel.js
  Routes/expenseRoute.js
  Routes/goalRoute.js
  Routes/homeRoute.js
  Routes/incomeRoute.js
  Routes/joinTeamRoute.js
  Routes/teamsRoute.js
  Routes/transferRoute.js
  Routes/userRegisterRoutes.js
  controllers/ExpenseController.js
  controllers/bankcontroller.js
  controllers/goalController.js
  controllers/incomeController.js
  controllers/joinTeamController.js
  controllers/savingcontroller.js
  controllers/teamsController.js
  controllers/transferController.js
  controllers/userRegisterController.js
  controllers/welcome.js
  index.js
  package-lock.json
  package.json
  routes/bankroute.js
  routes/savingroute.js
Labels: need review

#31 home page update
  Routes/homeRoute.js
Labels: need review

#33 other changes for.....
  Routes/userRegisterRoutes.js
Labels: need review

#34 expenses added
  index.js
Labels: need review

#35 expenses udated
  Routes/expenseRoute.js
Labels: ready to merge, need review

#13 Node mails
  Routes/expenseRoute.js
  controllers/userRegisterController.js
  controllers/welcome.js
  index.js
  package-lock.json
  package.json
Labels: ready to merge, need rebase

#36 Node mails
  Routes/expenseRoute.js
  controllers/userRegisterController.js
  controllers/welcome.js
  index.js
  package-lock.json
  package.json
Labels: ready to merge

#37 add createteam endpoint
  Routes/teamsRoute.js
  index.js
Labels: need review

#38 fix node mail
  Models/savingModel.js
  controllers/userRegisterController.js
  index.js
  package-lock.json
  package.json
Labels: ready to merge

#39 changes for deployment
  Routes/incomeRoute.js
  index.js
Labels: ready to merge

#40 others
  index.js
Labels: ready to merge

#41 changes
  controllers/welcome.js
Labels: ready to merge

#28 confirmation
  Models/confirmation.js
  Routes/response.js
  Routes/userRegisterRoutes.js
  controllers/confirmation.js
  controllers/response.js
  controllers/userRegisterController.js
  index.js
  package.json
Labels: ready to merge

#43 i'm able to get all the teams created
  Routes/teamsRoute.js
  controllers/teamsController.js
  index.js
Labels: ready to merge

#45 Comfirmation
  Models/confirmation.js
  Routes/response.js
  Routes/userRegisterRoutes.js
  controllers/confirmation.js
  controllers/response.js
  controllers/userRegisterController.js
  index.js
  package.json
Labels: ready to merge

#46 Ft confirmation email
  Routes/confirmSmsRoute.js
  controllers/confirmSmsController.js
  index.js
Labels: ready to merge

#48 account transaction notification to user
  Models/User1.js
  Routes/transactionRoutes.js
  config/emailConfig.js
  controllers/transactionController.js
  index.js
  package-lock.json
  package.json
  services/notificationService.js
Labels: ready to merge

#50 remove all controller importation error
  Routes/goalRoute.js
  routes/bankroute.js
  routes/savingroute.js
Labels: ready to merge

#51 Codes of fixed develop
  controllers/confirmSmsController.js
  index.js
  package.json
Labels: enhancement

#54 i have collected simple error
  index.js
Labels: enhancement

#55 this is the v2 of fixed develop that has the previous codes that work
  Models/bankModel.js
  Routes/expenseRoute.js
  Routes/transferRoute.js
  controllers/ExpenseController.js
  controllers/transferController.js
  index.js
Labels: ready to merge

#56 changes for deployment
  index.js
Labels: ready to merge

#57 depployment updates
  index.js
Labels: ready to merge

#58 deployment correction
  index.js
Labels: ready to merge

#59 deployment correction
  index.js
Labels: ready to merge

#60 deployment correction
  index.js
Labels: ready to merge

#61 changes for deployment
  controllers/savingcontroller.js
  index.js
  routes/savingroute.js
Labels: ready to merge

#62 deployment updates
  index.js
Labels: ready to merge

#63 changes on deployment
  index.js
Labels: ready to merge

#64 deployment updates
  index.js
Labels: ready to merge

#65 I have modified user register codes to check email and password when…
  controllers/userRegisterController.js
Labels: ready to merge

#66 fixed errors for expenses and income
  Models/ExpenseModel.js
  Models/incomeModel.js
  Routes/incomeRoute.js
  controllers/ExpenseController.js
  controllers/incomeController.js
Labels: ready to merge

#67 Fixed deployment6
  controllers/transferController.js
  controllers/userRegisterController.js
Labels: ready to merge

#69 changes on income side
  controllers/incomeController.js
Labels: ready to merge

#68 I have modified codes of joining the teams
  controllers/joinTeamController.js
Labels: ready to merge

#70 added a readGoal in controller
  Routes/goalRoute.js
  controllers/goalController.js
Labels: ready to merge

#71 those were the stashed codes but they have working codes
  Models/goalModel.js
  controllers/goalController.js
  controllers/incomeController.js
  controllers/transferController.js
Labels: ready to merge

#72 we have staged changes whihc was causing errors
  controllers/incomeController.js
  controllers/transferController.js
Labels: ready to merge

#73 i have modified error to read goals
  controllers/goalController.js
Labels: ready to merge

#74 fixed the dotenv file for now it should be working
  .env
  .gitignore
  controllers/joinTeamController.js
  controllers/userRegisterController.js
Labels: ready to merge

#75 Fixed dotenv
  .env
  .gitignore
  controllers/userRegisterController.js
Labels: ready to merge

#77 now we have colleted the codes to join teams
  Models/teamsModel.js
  controllers/confirmSmsController.js
  controllers/joinTeamController.js
Labels: ready to merge

#79 fix nodemail issue
  controllers/userRegisterController.js
Labels: ready to merge

#80 updates on nodemail
  controllers/userRegisterController.js
Labels: ready to merge

#81 fixed join team logic
  controllers/joinTeamController.js
Labels: ready to merge

#82 fix nodemail
  controllers/userRegisterController.js
Labels: ready to merge

#83 ability to withdraw from team to pA
  .env
  controllers/withdrawController.js
  index.js
Labels: ready to merge

#84 withdraw updates
  Models/teamsModel.js
Labels: ready to merge

#85 update team alert message
  controllers/joinTeamController.js
Labels: ready to merge
